# Generated by Django 2.0.6 on 2018-10-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='reg_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
