# Generated by Django 2.0.6 on 2018-10-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_guestbook_reg_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbook',
            old_name='email',
            new_name='message',
        ),
    ]
